remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links

title: Titanium Computing DevOps Documentation
description: Comprehensive guides for modern DevOps practices and tools by Titanium Computing
show_downloads: false

# Enable GitHub Flavored Markdown
markdown: GFM
highlighter: rouge

# Navigation
nav:
  - title: Main
    url: /
  - title: Containerization
    url: /containerization/
  - title: CI/CD
    url: /ci-cd/
  - title: Cloud
    url: /cloud/
  - title: Infrastructure as Code
    url: /iac/
  - title: Monitoring
    url: /monitoring/
  - title: Security
    url: /security/

# Default layout
defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
